#!/bin/bash
declare -a cydia
cydia=($CYDIA)

echo "StashUnified Version 2.0.0"
echo "Copyright 2016, CoolStar. Updated 2026, PlayDay."

if [ ! -x /usr/libexec/cydia/move.sh ]; then
	echo "Warning: /usr/libexec/cydia/move.sh not found, skipping directory stashing."
	echo "  Install Cydia to enable stashing of preference bundles and toolchains."
	exit 0
fi

echo "stashing preference bundles..."
/usr/libexec/cydia/move.sh /Library/PreferenceBundles #Preference Bundles
/usr/libexec/cydia/move.sh /Library/PreferenceLoader #Preference Bundles
echo "stashing 3rd party binaries/libraries..."
/usr/libexec/cydia/move.sh /usr/local/bin #perl and some others
/usr/libexec/cydia/move.sh /usr/local/lib #perl and some others
echo "stashing developer toolchains..."
/usr/libexec/cydia/move.sh /usr/share/llvm #LLVM + Clang for developers
echo "Done. Enjoy your free space for tweaks!"

if mount | grep -q "/private/var (.*nosuid"; then
	if [[ ${CYDIA+@} ]]; then
		eval "echo 'finish:reboot' >&${cydia[0]}"
	else
		echo "Please reboot your device after installation!"
		echo "Please reboot your device after installation!"
		echo "Please reboot your device after installation!"
		echo "Please reboot your device after installation!"
	fi
fi
exit 0
